# Generated by Django 4.2.16 on 2024-11-08 04:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.UUIDField(auto_created=True, unique=True)),
                ("area_name_cn", models.CharField(max_length=15, unique=True)),
                (
                    "area_name_en",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("lat_from", models.FloatField()),
                ("lat_to", models.FloatField()),
                ("lng_from", models.FloatField()),
                ("lng_to", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.UUIDField(auto_created=True, unique=True)),
                ("area_uuid", models.UUIDField(unique=True)),
                ("station_no_start", models.CharField(max_length=256)),
                ("station_no_end", models.CharField(max_length=256)),
                (
                    "bike_types",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Type1", "Generation 1"),
                            ("Type2", "Generation 2"),
                            ("Type3", "E-Bike"),
                        ],
                        max_length=50,
                    ),
                ),
                ("member_count", models.BigIntegerField()),
                ("ride_count1", models.BigIntegerField()),
                ("ride_count2", models.BigIntegerField()),
                ("visit_count", models.BigIntegerField()),
            ],
        ),
    ]
