# Generated by Django 4.2.16 on 2024-11-08 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("taiwan_area_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areainfo",
            name="_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="areainfo",
            name="area_name_cn",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="areainfo",
            name="area_name_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="serviceinfo",
            name="_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
