# Generated by Django 4.2.16 on 2024-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taiwan_area_info",
            "0002_alter_areainfo__id_alter_areainfo_area_name_cn_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="areainfo",
            name="area_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="areainfo",
            name="area_code_2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
