# Generated by Django 4.2.16 on 2024-11-10 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("taiwan_area_info", "0003_areainfo_area_code_areainfo_area_code_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("area_uuid", models.UUIDField()),
                (
                    "district_tw",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "district_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
    ]
