# Generated by Django 4.2.16 on 2024-11-10 15:12

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoubikeStationsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("area_uuid", models.UUIDField()),
                ("district_uuid", models.UUIDField()),
                ("name_tw", models.CharField(max_length=256)),
                ("name_en", models.CharField(max_length=256)),
                ("address_tw", models.CharField(max_length=256)),
                ("address_en", models.CharField(max_length=256)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("station_no", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="YoubikeStationsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_at", models.DateTimeField(auto_created=True)),
                (
                    "_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("station_uuid", models.UUIDField()),
                ("parking_spaces", models.BigIntegerField()),
                ("available_spaces", models.BigIntegerField()),
                ("record_time", models.DateTimeField()),
                (
                    "station_status",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[(1, "work"), (2, "not work")], max_length=3
                    ),
                ),
            ],
        ),
    ]
