# Generated by Django 4.2.16 on 2024-11-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youbike", "0002_alter_youbikestationsstatus_station_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youbikestationsstatus",
            name="update_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2024, 11, 10, 15, 35, 27, 777710),
            ),
        ),
    ]
