# Generated by Django 4.2.16 on 2024-11-10 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youbike", "0003_alter_youbikestationsstatus_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youbikestationsstatus",
            name="update_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2024, 11, 10, 15, 39, 47, 416846, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
