# Generated by Django 4.2.16 on 2024-11-10 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("youbike", "0004_alter_youbikestationsstatus_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youbikestationsstatus",
            name="update_at",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
    ]
