# Generated by Django 4.2.16 on 2024-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="e_mail",
            field=models.EmailField(
                default="default@default.com", max_length=254, unique=True
            ),
        ),
    ]
