# Generated by Django 4.2.16 on 2024-11-13 03:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObservationStationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("station_name", models.CharField(max_length=256, unique=True)),
                ("station_id", models.CharField(blank=True, max_length=256, null=True)),
                ("altitude", models.FloatField()),
                ("area_uuid", models.UUIDField()),
                ("district_uuid", models.UUIDField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PrecipitationObservationStatics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_created=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("station_uuid", models.UUIDField()),
                ("observe_time", models.DateField(editable=False, max_length=256)),
                ("precipi_obstime", models.FloatField()),
                ("precipi_past_10_min", models.FloatField()),
                ("precipi_past_1_hr", models.FloatField()),
                ("precipi_past_3_hr", models.FloatField()),
            ],
        ),
    ]
