# Generated by Django 4.2.16 on 2024-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationstationinfo",
            name="station_id",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="observationstationinfo",
            name="station_name",
            field=models.CharField(max_length=256),
        ),
    ]
