name: Run Crawler Every 5 Minutes

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/5 * * * *"

jobs:
  postgres-and-crawler:
    runs-on: ubuntu-latest
    environment: youbikesuggest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject prod env settings with database public host
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "<"
          tokenSuffix: ">"
          files: '["**/adminconfig/.env"]'
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}
          DEFAULT_DATABASE_HOST: ${{ secrets.DEFAULT_DATABASE_HOST }}
          DEFAULT_DATABASE_NAME: ${{ secrets.DEFAULT_DATABASE_NAME }}
          DEFAULT_DATABASE_PASSWORD: ${{ secrets.DEFAULT_DATABASE_PASSWORD }}
          DEFAULT_DATABASE_PORT: ${{ secrets.DEFAULT_DATABASE_PORT }}
          DEFAULT_DATABASE_USER: ${{ secrets.DEFAULT_DATABASE_USER }}
          DEFAULT_DATABASE_URL: ${{ secrets.DEFAULT_DATABASE_URL }}
          CENTRAL_WEATHER_ADMIN_API_TOKEN: ${{ secrets.CENTRAL_WEATHER_ADMIN_API_TOKE }}
      - name: Run database migrations
        run: |
          python manage.py migrate
      - name: Test URL access
        run: |
          curl -v https://apis.youbike.com.tw/json/station-yb1.json
          curl -v https://apis.youbike.com.tw/json/station-yb2.json
          curl -v https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0002-001?Authorization=${{ secrets.CENTRAL_WEATHER_ADMIN_API_TOKE }}&format=JSON

      - name: Run crawler script
        run: |
          python adminconfig/utils/crawlers.py
