name: Run Crawler Every 5 Minutes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  postgres-and-crawler:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DEFAULT_DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DEFAULT_DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DEFAULT_DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U youbike_user"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject prod env settings with database public host
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "DATABASE_URL=${{ secrets.DEFAULT_DATABASE_URL }}" >> .env

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.DEFAULT_DATABASE_USER }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done

      - name: Run database migrations
        run: |
          python manage.py migrate

      - name: Run crawler script
        run: |
          python adminconfig/utils/crawlers.py
