name: Run Crawler Every 5 Minutes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  postgres-and-crawler:
    runs-on: ubuntu-latest
    environment: youbikesuggest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: youbike_user
          POSTGRES_PASSWORD: L8C7i1RdoTUoFk0fL6JP1VPoRa9SG1AR
          POSTGRES_DB: youbike
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U youbike_user"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject prod env settings with database public host
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "DATABASE_URL=postgresql://youbike_user:L8C7i1RdoTUoFk0fL6JP1VPoRa9SG1AR@127.0.0.1:5432/youbike" >> .env

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U youbike_user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done
      - name: Inject prod env settings with database public host
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "<"
          tokenSuffix: ">"
          files: '["**/adminconfig/.env"]'
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}
          DEFAULT_DATABASE_HOST: ${{ secrets.DEFAULT_DATABASE_HOST }}
          DEFAULT_DATABASE_NAME: ${{ secrets.DEFAULT_DATABASE_NAME }}
          DEFAULT_DATABASE_PASSWORD: ${{ secrets.DEFAULT_DATABASE_PASSWORD }}
          DEFAULT_DATABASE_PORT: ${{ secrets.DEFAULT_DATABASE_PORT }}
          DEFAULT_DATABASE_USER: ${{ secrets.DEFAULT_DATABASE_USER }}
          DEFAULT_DATABASE_URL: postgresql://${{ secrets.DEFAULT_DATABASE_USER }}:${{ secrets.DEFAULT_DATABASE_PASSWORD }}@127.0.0.1:5432/${{ secrets.DEFAULT_DATABASE_NAME }}

      - name: Run database migrations
        run: |
          python manage.py migrate
      - name: Test URL access
        run: |
          curl -v https://apis.youbike.com.tw/json/station-yb1.json
          curl -v https://apis.youbike.com.tw/json/station-yb2.json

      - name: Run crawler script
        run: |
          python adminconfig/utils/crawlers.py
